# Fly.io app config
app = "tomagotchi"
primary_region = "hkg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5057"
  HOST = "0.0.0.0"

[[services]]
  protocol = "tcp"
  internal_port = 5057
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"


